---
title: "EDA DataCo Global Supply Chain"
author: "Angga Chandra"
date: '2023-06-01'
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE, warning=FALSE,message=FALSE}
library(dplyr) 
library(plotly) 
library(glue)
library(scales) 
library(tidyr) 
library(ggpubr) 
library(lubridate)
library(echarts4r)
library(DT)
```

# 1. Dataset
The dataset used for this exploratory data analysis is DataCo Global Supply Chain from https://www.kaggle.com/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis
```{r}
scm <- read.csv("supply_chain.csv")
```

```{r}
    sum_sales <- scm %>%
      #mutate(date = as_date(order_date))%>%
      mutate(date = lubridate::floor_date(order_date, "month")) %>%
      group_by(date)%>%
      summarise(total_sales = sum(sales))


    line1 <- sum_sales %>%
      e_charts(date) %>%
      e_line(total_sales) %>%
      e_legend(orient = "horizontal",
               bottom = "bottom"
      ) %>%
      e_tooltip(trigger = 'axis') %>%
      e_title(text = "Sales Trend",
              left = "center")
```
```{r}
sum_sales
```


Preview of the top row data
```{r}
head(scm)
```

Preview of the bottom row data
```{r}
tail(scm)
```

Data type of each column
```{r}
glimpse(scm)
```

# 2. Data Preprocessing
changing the data type for order_date and shipping_date column to date
```{r}
scm$order_date <- mdy_hms(scm$order_date) 
scm$shipping_date <- mdy_hms(scm$shipping_date) 
```

```{r}
unique(scm$order_country)
```

unique(data$Product)
```{r}
scm$order_country[scm$order_country == 'M\xe9xico'] <- 'Mexico'
```


```{r}
sum(scm$sales)
```
```{r}
nrow(scm)
```
```{r}
round(mean(scm$total_shipping_days))
```

```{r}
sales_cat <- scm %>%
  group_by(category_name) %>%
  summarise(total_sales = sum(sales)) %>%
  top_n(5) %>%
  arrange(desc(total_sales))
sales_cat
```

```{r}
bar1 <- sales_cat %>%
  e_charts(category_name) %>%
  e_bar(total_sales, 
        name = "total_sales", 
        legend = FALSE
  ) %>%
  e_labels(position = "top", 
           formatter = htmlwidgets::JS("
                        function (params) {
                          return (parseFloat(params.value[1]).toLocaleString('en-US'));
                        }
                      ")
  ) %>%
  e_y_axis(show = FALSE) %>%
  e_x_axis(axisTick = FALSE) %>%
  e_tooltip(formatter = e_tooltip_item_formatter(locale = 'en-US')) %>%
  e_color("#163ec2") %>%
  e_title(text = "Top 5 Sales by Category",
          left = "center")

bar1

```

```{r}
segm_chart <- scm %>%
  group_by(customer_segment) %>%
  summarise(n = n()) %>%
  rename(
    "Total Data" = n
  ) 

segm_chart

```

```{r}
pie1 <- segm_chart %>%
  e_charts(customer_segment) %>%
  e_pie(`Total Data`, radius = c("50%", "70%")) %>%
  e_title("Customer Segment \n Composition",
          left = "center",
          top = "center") %>%
  e_tooltip() %>%
  e_labels(show = TRUE,
           formatter = "{b} \n {d}%",
           position = "outside"
           ) %>%
  e_legend(orient = "vertical",
           left = "right",
           top = "50px")
pie1
```
```{r}
shipping_mode_chart <- scm %>%
  group_by(shipping_mode) %>%
  summarise(n = n()) %>%
  rename(
    "Total Data" = n
  ) 

shipping_mode_chart

```

```{r}
pie2 <- shipping_mode_chart %>%
  e_charts(shipping_mode) %>%
  e_pie(`Total Data`, radius = c("50%", "70%")) %>%
  e_title("Shipping Mode \n Composition",
          left = "center",
          top = "center") %>%
  e_tooltip() %>%
  e_labels(show = TRUE,
           formatter = "{b} \n {d}%",
           position = "outside"
           ) %>%
  e_legend(orient = "vertical",
           left = "right",
           top = "50px")
pie2
```




```{r}
order_country  <- scm %>%
  group_by(order_country) %>%
  summarise(n = n()) %>%
  rename(
    "total_order" = n
  ) %>%
  top_n(5) %>%
  arrange(desc(total_order))
order_country
```

```{r}
bar2 <- order_country %>%
  e_charts(order_country) %>%
  e_bar(total_order, 
        name = "total_order", 
        legend = FALSE
  ) %>%
  e_labels(position = "top", 
           formatter = htmlwidgets::JS("
                        function (params) {
                          return (parseFloat(params.value[1]).toLocaleString('id-ID'));
                        }
                      ")
  ) %>%
  e_y_axis(show = FALSE) %>%
  e_x_axis(axisTick = FALSE) %>%
  e_tooltip(formatter = e_tooltip_item_formatter(locale = 'id-ID')) %>%
  e_color("#163ec2") %>%
  e_title(text = "Top 5 Country with Most Order",
          left = "center")

bar2
```


```{r}
del_chart <- scm %>%
  group_by(delivery_status) %>%
  summarise(n = n()) %>%
  rename(
    "total_data" = n
  )  %>%
  arrange(total_data)

del_chart

```

```{r}
pie3 <- del_chart %>%
  e_charts(delivery_status) %>%
  e_pie(`total_data`, radius = c("50%", "70%")) %>%
  e_title("Delivery Status \n Composition",
          left = "center",
          top = "center") %>%
  e_tooltip() %>%
  e_labels(show = TRUE,
           formatter = "{b} \n {d}%",
           position = "outside"
           ) %>%
  e_legend(orient = "vertical",
           left = "right",
           top = "50px")
pie3
```

```{r}
order_cat  <- scm %>%
  group_by(category_name) %>%
  summarise(n = n()) %>%
  rename(
    "total_order" = n
  ) %>%
  top_n(5) %>%
  arrange(desc(total_order))
order_cat
```

```{r}
bar3 <- order_cat %>%
  e_charts(category_name) %>%
  e_bar(total_order, 
        name = "total_order", 
        legend = FALSE
  ) %>%
  e_labels(position = "top", 
           formatter = htmlwidgets::JS("
                        function (params) {
                          return (parseFloat(params.value[1]).toLocaleString('id-ID'));
                        }
                      ")
  ) %>%
  e_y_axis(show = FALSE) %>%
  e_x_axis(axisTick = FALSE) %>%
  e_tooltip(formatter = e_tooltip_item_formatter(locale = 'id-ID')) %>%
  e_color("#163ec2") %>%
  e_title(text = "Top 5 Category with Most Order",
          left = "center")

bar3
```

```{r}
sum_sales <- scm %>%
  mutate(date = as_date(order_date)) %>%
  group_by(date) %>%
  summarise(total_sales = sum(sales))
sum_sales
```

```{r}
line1 <- sum_sales %>%
  e_charts(date) %>%
  e_line(total_sales) %>%
  e_legend(orient = "horizontal",
           bottom = "bottom"
  ) %>%
  e_tooltip(trigger = 'axis') %>%
  e_title(text = "Sales Trend",
          left = "center")
line1
```

```{r}
sales_dist <- scm
```

```{r}
hist1 <- sales_dist %>%
  e_charts() %>%
  e_histogram(serie = sales, name = "histogram") %>%
  e_density(
    serie = sales,
    areaStyle = list(opacity = .4), 
    smooth = TRUE, 
    name = "density", 
    y_index = 1
  ) %>%
  e_y_axis(index = 1, show = FALSE) %>%
  e_title(text = "Sales Distribution",
          left = "center") %>%
  e_legend(top = "9%") %>%
  e_tooltip(trigger = "axis") %>%
  e_hide_grid_lines(which = "x")
hist1
```
```{r}
ship_date_duration_dist  <- scm %>%
  group_by(total_shipping_days) %>%
  summarise(n = n()) %>%
  rename(
    "total" = n
  )
ship_date_duration_dist
```

```{r}
bar4 <- ship_date_duration_dist %>%
  e_charts(total_shipping_days) %>%
  e_bar(total, 
        name = "total", 
        legend = FALSE
  ) %>%
  e_labels(position = "top"
  ) %>%
  e_y_axis(show = FALSE) %>%
  e_x_axis(axisTick = FALSE) %>%
  e_tooltip() %>%
  e_color("#163ec2") %>%
  e_title(text = "Ship Duration Distribution",
          left = "center")

bar4
```

```{r}
 ship <- scm %>%
  filter(delivery_status == "Late delivery") %>%
  group_by(shipping_mode) %>%
  summarise(n = n()) %>%
  rename(
    "total_late_delivery" = n
  )  %>%
  arrange(total_late_delivery)

 ship
```
```{r}
    bar6 <- ship %>%
      e_charts(shipping_mode) %>%
      e_bar(total_late_delivery, 
            name = "total_late_delivery", 
            legend = FALSE
      ) %>%
      e_labels(position = "top"
      ) %>%
      e_y_axis(show = FALSE) %>%
      e_x_axis(axisTick = FALSE) %>%
      e_tooltip() %>%
      e_color("#163ec2") %>%
      e_title(text = "Total Late Delivery by shipping_mode",
              left = "center")
bar6
```




