library(shiny)
library(shinydashboard)
library(dplyr) 
library(plotly) 
library(glue)
library(scales) 
library(tidyr) 
library(ggpubr) 
library(lubridate)
library(echarts4r)
library(DT)
library(shinyWidgets)
library(rlang)
library(tidyverse)
library(caret)
library(reshape2)
library(formattable)

options(scipen = 9999)

scm <- read.csv("supply_chain.csv")
scm$order_date <- mdy_hms(scm$order_date) 
scm$shipping_date <- mdy_hms(scm$shipping_date) 
scm$order_country[scm$order_country == 'M\xe9xico'] <- 'Mexico'
selectpiechart <- c("customer_segment", "type", "delivery_status", "shipping_mode")
selectbarchart <- c("category_name", "customer_city", "department_name", "order_status")
selectlinechart <- c("day", "week", "month")
selectbarchart2 <- c("customer_segment", "type", "shipping_mode")